---
- name: Cloning dotfiles
  git:
    repo: "{{ dotfiles_repo }}"
    dest: ~/.dotfiles
- name: Setting up dotfiles links
  shell: rcup -v
- name: Installing tmux plugins manager
  git:
    repo: "{{ tpm_repo }}"
    dest: ~/.tmux/plugins/tpm
    depth: 1
- name: Setting zsh as default shell
  shell: chsh -s $(which zsh)
  ignore_errors: yes
...